### ISSUE TITLE
[Bug] Exception error (clickInventory) when item is gifted

### ISSUE THREAD

**Issue by mrfloris** [mk7a/ItemSoulBind-Info#1]
A player is able to send the item through a market place or a gift or other unexpected means, at which point the soul bound item not belonging to them ends up in the inventory of the other player, which triggers the below error apparently. I am trying to prevent it by blacklisting the lore in the other plugins, but i think the error should be 'caught'.

```
>ver ItemSoulBind
[10:00:06 INFO]: ItemSoulBind version 0.3.0
[10:00:06 INFO]: Bind items for a single player's use only
[10:00:06 INFO]: Website: https://www.mk7a.com
[10:00:06 INFO]: Author: mk7a
>ver
[10:00:06 INFO]: This server is running CraftBukkit version git-Spigot-3cb9dcb-8d8475f (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[10:00:06 INFO]: Checking version, please wait...
[10:00:07 INFO]: You are running the latest version
>
```

**To Reproduce**
Someone does /gift player (sending the item they're holding that's soul bound to another player who then accepts it and has the item in their inventory)

**Expected behavior**
Unable to use the item - you cannot use this item, soul bound to someone else

```
[09:58:07 INFO]: ilujf issued server command: /gift open
[09:58:08 ERROR]: Could not pass event InventoryClickEvent to ItemSoulBind v0.3.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2123) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.mk7a.soulbind.ItemProtectionListener.invClick(ItemProtectionListener.java:45) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8d8475f]
        ... 15 more
>
```

**Comment by mk7a** [comment]
Thanks for submitting a report.

What plugin are you using for /gift ?

To reproduce what I understand is: 
Player 1 soulbinds an item to themself, then gifts it to Player 2 through that plugin, producing the error - is this correct?

**Comment by mrfloris** [comment]
https://www.spigotmc.org/resources/rcmailbox-send-items-to-online-offline-players-1-7-1-13.60636/

yes.

**Comment by mk7a** [comment]
I have released a hotfix that fixes this exception.

In a future version I will add a system to combat moving soulbound items into player inventories through other plugins.

Thank you for bringing up this issue.
